// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/database/health": {
            "get": {
                "description": "Gets the state of the connected database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "database"
                ],
                "summary": "Returns the state of the connected database",
                "responses": {
                    "200": {
                        "description": "Returns database health status",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/database/migrations": {
            "post": {
                "description": "Runs the database migrations from GORM",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "database"
                ],
                "summary": "Runs the migrations from GORM",
                "responses": {
                    "200": {
                        "description": "Retuns success message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Retuns any errors",
                        "schema": {}
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "Gets all the users",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Returns all the users",
                "responses": {
                    "200": {
                        "description": "Returns a pagenated list of users",
                        "schema": {
                            "$ref": "#/definitions/github_com_CallumLewisGH_Generic-Service-Base_internal_domain_models.User"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_CallumLewisGH_Generic-Service-Base_internal_domain_models.User": {
            "type": "object",
            "properties": {
                "bio": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deactivatedAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "email": {
                    "type": "string"
                },
                "emailVerified": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "isActive": {
                    "description": "Status",
                    "type": "boolean"
                },
                "isBanned": {
                    "type": "boolean"
                },
                "lastLogin": {
                    "type": "string"
                },
                "locale": {
                    "description": "Preferences",
                    "type": "string"
                },
                "profilePicture": {
                    "description": "Profile",
                    "type": "string"
                },
                "timezone": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "username": {
                    "description": "Authentication",
                    "type": "string"
                }
            }
        },
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Generic-Service-Base API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
