info:
  contact: {}
  title: Generic-Service-Base API
  version: "1.0"
paths:
  /database/health:
    get:
      description: Gets the state of the connected database
      produces:
      - application/json
      responses:
        "200":
          description: Returns database health status
          schema:
            type: string
      summary: Returns the state of the connected database
      tags:
      - database
  /database/migrations:
    post:
      description: Runs the database migrations from GORM
      produces:
      - application/json
      responses:
        "200":
          description: Retuns success message
          schema:
            type: string
        "500":
          description: Retuns any errors
          schema: {}
      summary: Runs the migrations from GORM
      tags:
      - database
swagger: "2.0"
